version: "3"
services:
  db:
    image: postgres:alpine3.19
    restart: always
    environment:
      POSTGRES_PASSWORD: "PROD"
      POSTGRES_USER: "postgres"
      POSTGRES_DB: "postgres"
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready", "-d", "PROD", "-U", "postgres" ]
      interval: 5s
      timeout: 60s
      retries: 20
    user: postgres
    volumes:
      - db-data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
  backend:
    build: ./backend
    command: node --inspect=0.0.0.0:9229 ./dist/main.js
    depends_on:
      db:
        condition: service_healthy
    environment:
      DB_HOST: db
      DB_PORT: 5432
      DB_USER: postgres
      DB_PASSWORD: PROD
      DB_NAME: postgres
      PORT: 8080
      HOST: "0.0.0.0"
    ports:
      - "9229:9229" # debug port for node.js
  nginx:
    build:
      context: .
      dockerfile: ./nginx/Dockerfile
      target: server
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - backend
volumes:
  db-data: